# Generated by Django 4.1.1 on 2022-09-18 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_post_stars_post_type_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('date', models.DateField(auto_now_add=True, null=True)),
                ('stars', models.IntegerField(null=True)),
                ('type', models.IntegerField(choices=[(1, 'Animals'), (2, 'Cars'), (3, 'Recipes'), (4, 'Nature'), (5, 'Other')], null=True)),
            ],
        ),
    ]
